/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 43874f5d-f30f-4c08-aa3c-276a2e8da476

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib

set_option linter.mathlibStandardSet false

namespace Erdos646

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Given k+1 elements in (Z/2Z)^k, there exists a non-empty subset summing to 0. Lemma 1
-/
lemma exists_subset_sum_zero {k : ℕ} (v : Fin (k + 1) → (Fin k → ZMod 2)) :
  ∃ (I : Finset (Fin (k + 1))), I.Nonempty ∧ ∑ i ∈ I, v i = 0 := by
    have h_linear_dep : ¬ LinearIndependent (ZMod 2) v := by
      intro h
      have hdim := linearIndependent_le_basis (Pi.basisFun (ZMod 2) (Fin k)) v h
      simp_all +decide
    rw [Fintype.not_linearIndependent_iff] at h_linear_dep
    obtain ⟨g, hg, i, hi⟩ := h_linear_dep
    have h01 (x : ZMod 2) : x = 0 ∨ x = 1 := by
      have hxlt := x.val_lt
      have hx : x.val = 0 ∨ x.val = 1 := by omega
      exact hx.imp (ZMod.val_eq_zero x).mp (ZMod.val_eq_one (by decide) x).mp
    let I := Finset.univ.filter fun j => g j ≠ 0
    refine ⟨I, ⟨i, by simp [I, hi]⟩, ?_⟩
    calc
      ∑ j ∈ I, v j = ∑ j, if g j ≠ 0 then v j else 0 := by
        simp [I, Finset.sum_filter]
      _ = ∑ j, g j • v j := by
        apply Finset.sum_congr rfl
        intro j _
        rcases h01 (g j) with hj | hj
        · simp [hj]
        · simp [hj]
      _ = 0 := hg

/-
If n > 0 and v_p(n) <= M, then v_p(n + k * p^(M+1)) = v_p(n). Lemma 2
-/
lemma padicValNat_periodic_pos (p : ℕ) (hp : p.Prime) (n k M : ℕ) (hn : n > 0) (h : padicValNat p n ≤ M) :
  padicValNat p (n + k * p ^ (M + 1)) = padicValNat p n := by
    -- Let $v = v_p(n)$. We have $v \le M$.
    set v : ℕ := padicValNat p n with hv_def
    have hv_le_M : v ≤ M := h;
    -- Write $n = p^v \cdot u$ where $p \nmid u$.
    obtain ⟨u, hu⟩ : ∃ u : ℕ, n = p^v * u ∧ ¬ p ∣ u := by
      use n / p^v, by
        rw [ Nat.mul_div_cancel' ];
        exact pow_padicValNat_dvd, by
        rw [ Nat.dvd_div_iff_mul_dvd ];
        · rw [ ← pow_succ ];
          haveI := Fact.mk hp; rw [ padicValNat_dvd_iff_le ] ; aesop;
          positivity;
        · exact pow_padicValNat_dvd;
    -- Then $n + k p^{M+1} = p^v u + k p^{M+1} = p^v (u + k p^{M+1-v})$.
    have h_factor : n + k * p^(M + 1) = p^v * (u + k * p^(M + 1 - v)) := by
      rw [ hu.1, mul_add, mul_left_comm, ← pow_add, add_tsub_cancel_of_le ( by linarith ) ];
    -- Since $v \le M$, $M+1-v \ge 1$, so $p \mid p^{M+1-v}$.
    have h_div : ¬ p ∣ (u + k * p^(M + 1 - v)) := by
      rw [ Nat.dvd_add_left ( dvd_mul_of_dvd_right ( dvd_pow_self _ ( Nat.sub_ne_zero_of_lt ( by linarith ) ) ) _ ) ] ; tauto;
    haveI := Fact.mk hp; rw [ h_factor, padicValNat.mul ] <;> norm_num [ h_div ] ;
    · exact fun h => absurd h hp.ne_zero;
    · exact fun h => absurd h ( by rintro rfl; simp_all +singlePass )

/-
Definitions for the vector of valuations and the partial sum vector.
-/
def val_vec (k : ℕ) (p : Fin k → ℕ) (n : ℕ) : Fin k → ZMod 2 :=
  fun i => padicValNat (p i) n

def partial_sum (k : ℕ) (p : Fin k → ℕ) (n : ℕ) : Fin k → ZMod 2 :=
  fun i => padicValNat (p i) (Nat.factorial n)

/-
The sequence of valuation vectors is recurrent. Lemma 3
-/
lemma val_vec_recurrent (k : ℕ) (p : Fin k → ℕ) (hp : ∀ i, (p i).Prime) (b m : ℕ) (hb : b > 0) (hm : m > 0) :
  ∃ s > 0, ∀ j < b, val_vec k p (m + j) = val_vec k p (m + s + j) := by
    revert k p hp b m hb hm;
    -- Let's choose the maximum valuation $M_i$ for each prime $p_i$.
    intros k p hp b m hb hm
    set M := fun i => Finset.sup (Finset.range (b + m)) (fun n => padicValNat (p i) (n + 1)) with hM_def;
    -- Let $S = \prod_{i=1}^k p_i^{M_i + 1}$.
    set S := Finset.prod Finset.univ (fun i => p i ^ (M i + 1)) with hS_def;
    refine' ⟨ S, Finset.prod_pos fun i _ => pow_pos ( Nat.Prime.pos ( hp i ) ) _, fun j hj => _ ⟩ ; ext i ; simp +decide [ add_right_comm, val_vec ];
    -- By the properties of the p-adic valuation, we have that $v_{p_i}(m + j + S) = v_{p_i}(m + j)$ since $S$ is divisible by $p_i^{M_i + 1}$.
    have h_val_eq : padicValNat (p i) (m + j + S) = padicValNat (p i) (m + j) := by
      have h_val_eq : padicValNat (p i) (m + j) ≤ M i := by
        rw [hM_def]
        have hmem : m + j - 1 ∈ Finset.range (b + m) :=
          Finset.mem_range.mpr (by omega)
        have hle := Finset.le_sup
          (f := fun n => padicValNat (p i) (n + 1)) hmem
        simpa [Nat.sub_add_cancel (by omega : 1 ≤ m + j)] using hle
      convert padicValNat_periodic_pos ( p i ) ( hp i ) ( m + j ) ( S / p i ^ ( M i + 1 ) ) ( M i ) _ using 1;
      · rw [ Nat.div_mul_cancel ( show p i ^ ( M i + 1 ) ∣ S from Finset.dvd_prod_of_mem _ ( Finset.mem_univ _ ) ) ] ; aesop;
      · linarith;
    rw [ h_val_eq ]

/-
Inductive step for constructing a rich block. Given a block of length L that generates all subset sums of f, we can extend it to a block of length L' that generates all subset sums of f extended with a new vector.
-/
lemma rich_block_inductive_step (k : ℕ) (p : Fin k → ℕ) (hp : ∀ i, (p i).Prime) (N : ℕ) (m : ℕ) (L : ℕ) (f : Fin m → Fin k → ZMod 2)
  (h : ∀ (S : Finset (Fin m)), S.Nonempty → ∃ (l : ℕ), 0 < l ∧ l ≤ L ∧ ∑ i ∈ Finset.range l, val_vec k p (N + 1 + i) = ∑ i ∈ S, f i) :
  ∃ (L' : ℕ) (f' : Fin (m + 1) → Fin k → ZMod 2),
    ∀ (S : Finset (Fin (m + 1))), S.Nonempty → ∃ (l : ℕ), 0 < l ∧ l ≤ L' ∧ ∑ i ∈ Finset.range l, val_vec k p (N + 1 + i) = ∑ i ∈ S, f' i := by
      by_contra h_contra;
      obtain ⟨s, hs_pos, hs⟩ : ∃ s > 0, ∀ j < L, val_vec k p (N + 1 + j) = val_vec k p (N + 1 + s + j) := by
        by_cases hL : L = 0;
        · exact ⟨ 1, by norm_num, by norm_num [ hL ] ⟩;
        · convert val_vec_recurrent k p hp L ( N + 1 ) ( Nat.pos_of_ne_zero hL ) ( Nat.succ_pos _ ) using 1;
      refine' h_contra ⟨ s + L, Fin.snoc f ( ∑ i ∈ Finset.range s, val_vec k p ( N + 1 + i ) ), _ ⟩;
      intro S hS_nonempty
      by_cases hm : Fin.last m ∈ S;
      · -- Let $S' = S \setminus \{m\}$.
        obtain ⟨S', hS'⟩ : ∃ S' : Finset (Fin m), S = Finset.image (Fin.castSucc) S' ∪ {Fin.last m} := by
          use Finset.univ.filter (fun i => Fin.castSucc i ∈ S);
          ext i; by_cases hi : i = Fin.last m <;> simp +decide [ hi, hm ] ;
          exact ⟨ fun hi' => ⟨ ⟨ i.val, lt_of_le_of_ne ( Fin.le_last _ ) ( by simpa [ Fin.ext_iff ] using hi ) ⟩, by simpa [ Fin.ext_iff ] using hi', rfl ⟩, by rintro ⟨ a, ha, rfl ⟩ ; exact ha ⟩;
        by_cases hS'_nonempty : S'.Nonempty;
        · obtain ⟨ l, hl_pos, hl_le, hl ⟩ := h S' hS'_nonempty;
          refine' ⟨ s + l, by linarith, by linarith, _ ⟩;
          simp_all +decide [ Finset.sum_range_add, Finset.sum_image, Fin.snoc ];
          convert hl using 1;
          exact Finset.sum_congr rfl fun i hi => by rw [ show N + 1 + ( s + i ) = N + 1 + s + i by ring, hs i ( by linarith [ Finset.mem_range.mp hi ] ) ] ;
        · use s; aesop;
      · -- Since $Fin.last m \notin S$, we can consider $S$ as a subset of $Fin m$.
        obtain ⟨S', hS'⟩ : ∃ S' : Finset (Fin m), S = Finset.image (fun i => Fin.castSucc i) S' := by
          use Finset.univ.filter (fun i => Fin.castSucc i ∈ S);
          ext i; simp [Finset.mem_image];
          exact ⟨ fun hi => ⟨ ⟨ i.val, lt_of_le_of_ne ( Fin.le_last _ ) ( by rintro h; exact hm <| by convert hi; aesop ) ⟩, by simpa [ Fin.ext_iff ] using hi, rfl ⟩, by rintro ⟨ a, ha, rfl ⟩ ; exact ha ⟩;
        obtain ⟨ l, hl_pos, hl_le, hl ⟩ := h S' ( by simpa [ hS' ] using hS_nonempty ) ; use l; simp_all +decide [ Finset.sum_image ] ;
        linarith

/-
For any m, there exists a length L and vectors f_0, ..., f_{m-1} such that any non-empty subset sum of f_i's is realizable as a prefix sum of the valuation vector sequence starting at N+1, with positive length.
-/
lemma exists_rich_block (k : ℕ) (p : Fin k → ℕ) (hp : ∀ i, (p i).Prime) (N : ℕ) (m : ℕ) :
  ∃ (L : ℕ) (f : Fin m → Fin k → ZMod 2),
    ∀ (S : Finset (Fin m)), S.Nonempty → ∃ (l : ℕ), 0 < l ∧ l ≤ L ∧ ∑ i ∈ Finset.range l, val_vec k p (N + 1 + i) = ∑ i ∈ S, f i := by
      induction' m with m ih;
      · exact ⟨ 0, fun _ => 0, by simp +decide ⟩;
      · exact Exists.elim ih fun L hL => Exists.elim ( rich_block_inductive_step k p hp N m L hL.choose hL.choose_spec ) fun L' hL' => ⟨ L', hL'.choose, hL'.choose_spec ⟩

/-
There are infinitely many n such that n! is divisible by an even power of each of the p_i.
-/
theorem infinitely_many_even_factorial_exponents (k : ℕ) (p : Fin k → ℕ) (hp : ∀ i, (p i).Prime) (_h_distinct : Function.Injective p) :
  Set.Infinite { n | ∀ i, partial_sum k p n i = 0 } := by
    -- By induction on $N$, we can construct an infinite sequence of such $n$.
    have h_seq : ∀ N : ℕ, ∃ n > N, ∀ i, (partial_sum k p n i) = 0 := by
      intro N
      induction' N with N ih;
      · use 1; simp [partial_sum];
      · obtain ⟨ n, hn₁, hn₂ ⟩ := ih;
        obtain ⟨ L, f, hf ⟩ := exists_rich_block k p hp n ( k + 1 );
        obtain ⟨ S, hS₁, hS₂ ⟩ := exists_subset_sum_zero f;
        obtain ⟨ l, hl₁, hl₂, hl₃ ⟩ := hf S hS₁;
        refine' ⟨ n + l, by linarith, fun i => _ ⟩;
        -- By definition of partial_sum, we have:
        have h_partial_sum : partial_sum k p (n + l) i = partial_sum k p n i + ∑ j ∈ Finset.range l, val_vec k p (n + 1 + j) i := by
          unfold partial_sum val_vec; simp +decide [ add_assoc ] ;
          have h_partial_sum : ∀ m, padicValNat (p i) (Nat.factorial (n + m)) = padicValNat (p i) (Nat.factorial n) + ∑ j ∈ Finset.range m, padicValNat (p i) (n + 1 + j) := by
            intro m; induction m <;> simp_all +decide [ Nat.factorial, Finset.sum_range_succ ] ;
            haveI := Fact.mk ( hp i ) ; rw [ padicValNat.mul ( by positivity ) ( by positivity ) ] ; simp_all +decide [ add_comm, add_left_comm, add_assoc ] ;
          simp_all +decide [ add_assoc ];
        simp_all +decide [ funext_iff ];
    exact Set.infinite_of_forall_exists_gt fun N => by obtain ⟨ n, hn₁, hn₂ ⟩ := h_seq N; exact ⟨ n, hn₂, hn₁ ⟩

/-
Let $p_1, \dots, p_k$ be distinct primes. There are infinitely many $n$ such that $n!$
is divisible by an even power of each $p_i$.
-/
theorem erdos_646 (S : Finset ℕ) (hS : ∀ p ∈ S, Nat.Prime p) :
    Set.Infinite { n : ℕ | ∀ p ∈ S, Even (padicValNat p (Nat.factorial n)) } := by
  let L := S.toList
  let k := L.length
  let pr := fun (i : Fin k) => L.get i
  have hpr : ∀ i, Nat.Prime (pr i) := by
    intro i
    apply hS
    apply Finset.mem_toList.mp
    apply List.get_mem
  have h_distinct : Function.Injective pr := by
    intro i j h
    apply List.nodup_iff_injective_get.mp (Finset.nodup_toList S)
    exact h
  have h_inf := infinitely_many_even_factorial_exponents k pr hpr h_distinct
  convert h_inf using 1
  ext n
  simp only [Set.mem_setOf_eq]
  constructor
  · intro h i
    specialize h (pr i) (by apply Finset.mem_toList.mp; apply List.get_mem)
    unfold partial_sum
    rwa [ZMod.natCast_eq_zero_iff_even]
  · intro h q hq
    obtain ⟨i, hi⟩ := List.mem_iff_get.mp (Finset.mem_toList.mpr hq)
    have hi_val : pr i = q := hi
    specialize h i
    unfold partial_sum at h
    rwa [hi_val, ZMod.natCast_eq_zero_iff_even] at h

end

end Erdos646

namespace Submissions.Erdos646EvenFactorialValuations.Full

open scoped Nat

theorem proof :
    ∀ S : Finset ℕ, (∀ p ∈ S, p.Prime) →
      {n : ℕ | ∀ p ∈ S, Even (padicValNat p (n !))}.Infinite :=
  Erdos646.erdos_646

end Submissions.Erdos646EvenFactorialValuations.Full
